
name: KernelSU CI

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  ksu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check
      run: |
        sudo apt-get install curl git jq -y || sudo apt-get install curl git jq -y || true
        git config --global user.name Gabriel2392
        git config --global user.email gabriel824m@gmail.com
        latest_tag=$(curl -s https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r '.tag_name')
        touch latest_tag
        current_latest_tag=$(cat latest_tag)
        if [ "$latest_tag" == "$current_latest_tag" ]; then
          echo "No need to build new kernels"
          exit 1
        else
          echo "$latest_tag" > latest_tag
          git add latest_tag
          git commit -m "Update latest tag"
          git push
        fi
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
    - name: Build
      run: |
        echo "Updating package list..."
        sudo apt-get update -y &>/dev/null || sudo apt-get update -y &>/dev/null || true
        echo "Upgrading packages..."
        sudo apt-get upgrade -y &>/dev/null || sudo apt-get upgrade -y &>/dev/null || true
        echo "Installing some packages we want..."
        sudo apt-get install build-essential jq ccache bc clang gcc wget git -y &>/dev/null || sudo apt-get install build-essential jq ccache bc clang gcc wget git -y &>/dev/null || true
        git clone https://github.com/akhilnarang/scripts --depth=1 &>/dev/null
        bash scripts/setup/android_build_env.sh &>/dev/null
        rm -rf scripts
        echo "Installing python..."
        sudo apt-get install python3 python2 -y &>/dev/null ||  sudo apt-get install python3 -y &>/dev/null || sudo apt-get install python -y &>/dev/null || true
        chmod 0755 kernel.sh
        ./kernel.sh "${{ secrets.BOT_TOKEN }}" "${{ secrets.CHAT_ID }}"
